# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.process_button = QtWidgets.QPushButton(self.centralwidget)
        self.process_button.setGeometry(QtCore.QRect(300, 640, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.process_button.setFont(font)
        self.process_button.setStyleSheet("background-color: #50C878")
        self.process_button.setObjectName("process_button")
        self.result_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_text.setGeometry(QtCore.QRect(0, 410, 800, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_text.setFont(font)
        self.result_text.setObjectName("result_text")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 781, 381))
        self.image_label.setStyleSheet("background-color: rgb(143, 143, 143);")
        self.image_label.setObjectName("image_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.process_button.setText(_translate("MainWindow", "PROCESS"))
        self.result_text.setPlainText(_translate("MainWindow", "Result here..."))
        self.image_label.setText(_translate("MainWindow", "Image here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
